[package]
name = "rust_df_perf"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "6.0.0"
chrono = "0.4"
tokio = { version = "1.15.0", features = ["full"] }